on:
  push:
    branches:
      - "*"

jobs:
  aws_sam_validate_python36:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: sam validate
        uses: nktener0902/aws-sam-action/python3.6@feature/pip_update
        #uses: youyo/aws-sam-action/python3.6@v2
        with:
          sam_command: validate -t template.yaml
          actions_comment: true
          sam_version: 1.41.0
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-northeast-1'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  aws_sam_validate_python37:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: sam validate
        uses: nktener0902/aws-sam-action/python3.7@feature/add_libffi-dev
        #uses: youyo/aws-sam-action/python3.7@v2
        with:
          sam_command: validate -t template.yaml
          actions_comment: true
          sam_version: 1.59.0
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-northeast-1'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  aws_sam_validate_python38:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: sam validate
        uses: nktener0902/aws-sam-action/python3.8@feature/add_libffi-dev
        #uses: youyo/aws-sam-action/python3.8@v2
        with:
          sam_command: validate -t template.yaml
          actions_comment: true
          sam_version: 1.59.0
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-northeast-1'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
